package com.intentflow.core.model

import kotlinx.serialization.Serializable

/**
 * Execution target categories.
 */
@Serializable
enum class ExecutionTarget {
    ANDROID_PLUGIN,
    AI_PROVIDER,
    SYSTEM_DEEP_LINK,
    REST_API,
    LOCAL_RUNTIME
}

/**
 * Detailed capability target type selected by the Execution Planner.
 */
@Serializable
enum class ExecutionTargetCapability {
    ANDROID_PLUGIN,   // System Android capability plugins (Telephony, Contacts, Calendar, Maps, Settings)
    AI_PROVIDER,      // AI providers (Local Gemma, Google Gemini, OpenAI GPT, Anthropic Claude)
    SYSTEM_DEEP_LINK, // System or third-party deep link URIs
    REST_API,         // Remote backend REST endpoints
    LOCAL_RUNTIME     // On-device rule engine or offline local script
}

/**
 * Immutable execution plan object for an IntentObject.
 */
@Serializable
data class ExecutionPlan(
    val intentId: String,
    val target: ExecutionTarget = ExecutionTarget.ANDROID_PLUGIN,
    val targetHandlerId: String = "default",
    val resolvedParameters: Map<String, String> = emptyMap(),
    val requiresUserConfirmation: Boolean = false,
    val confirmationMessage: String? = null
) {
    fun validate(): ValidationResult {
        if (intentId.isBlank()) {
            return ValidationResult.Invalid("intentId cannot be blank")
        }
        if (targetHandlerId.isBlank()) {
            return ValidationResult.Invalid("targetHandlerId cannot be blank")
        }
        if (requiresUserConfirmation && confirmationMessage.isNullOrBlank()) {
            return ValidationResult.Invalid("confirmationMessage required when requiresUserConfirmation is true")
        }
        return ValidationResult.Valid
    }
}

/**
 * Strategy plan generated by the Execution Planner capability routing engine.
 */
@Serializable
data class CapabilityExecutionPlan(
    val intentId: String,
    val selectedCapability: ExecutionTargetCapability,
    val handlerId: String,
    val resolvedParameters: Map<String, String> = emptyMap(),
    val requiresUserConfirmation: Boolean = false,
    val confirmationMessage: String? = null,
    val fallbackCapability: ExecutionTargetCapability? = null
)
