package com.intentflow.engine.skill

import com.intentflow.core.model.ExecutionResult
import com.intentflow.core.model.IntentObject
import com.intentflow.core.model.SkillDefinition
import com.intentflow.plugin.api.PluginCapabilityRegistry
import io.mockk.mockk
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

class SkillEngineTest {

    private val pluginRegistry: PluginCapabilityRegistry = mockk(relaxed = true)
    private lateinit var bookFlightSkill: BookFlightSkill
    private lateinit var skillEngine: SkillEngine

    @Before
    fun setup() {
        bookFlightSkill = BookFlightSkill(pluginRegistry)
        skillEngine = DefaultSkillEngine(bookFlightSkill)
    }

    @Test
    fun testGetRegisteredSkillsContainsBookFlightSkill() {
        val skills = skillEngine.getRegisteredSkills()

        assertTrue(skills.isNotEmpty())
        assertEquals("skill.book_flight", skills.first().skillId)
    }

    @Test
    fun testExecuteSkillFlow() = runBlocking {
        val intentObject = IntentObject("1", "travel.book_flight", "travel")
        val result = skillEngine.executeSkill("skill.book_flight", intentObject).first()

        assertNotNull(result)
        assertTrue(result is ExecutionResult.Success)
    }

    @Test
    fun testRegisterAiGeneratedSkill() = runBlocking {
        val aiSkill = SkillDefinition(
            skillId = "skill.ai_custom",
            displayName = "Custom AI Skill",
            description = "Generated by LLM",
            isAiGenerated = true
        )

        skillEngine.registerAiGeneratedSkill(aiSkill)

        val skills = skillEngine.getRegisteredSkills()
        assertTrue(skills.any { it.skillId == "skill.ai_custom" && it.isAiGenerated })
    }
}
